# 自动合并dependabot相关PR

name: Auto Merge Dependabot PR

on:
  pull_request:
    branches: [ master ]

jobs:
  # 合并PR
  merge-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      if ${{ GITHUB_ACTOR	=== 'dependabot' }}
      - uses: actions/checkout@master
      - run: git pull
      - run: git merge ${{ GITHUB_REF }}
  testing: 
    needs: [merge-pr]
    runs-on:  ubuntu-latest
    steps: 
      - run: npm install
      - run: npm run test
  bump-version: 
    needs: [merge-pr, testing]
  release:
    needs: [bump-version]
    runs-on: ubuntu-latest
    steps:
      - run: npm run changelog
      - run: npm version patch
      - run: git add .
      - run: git commit -m "release"
      - run: git push
      - run: npm publish
